{{- if .Values.jenkins.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if .Values.cluster.ingress.annotations }}
{{ toYaml .Values.cluster.ingress.annotations | indent 4 }}
{{- end }}
{{- if .Values.jenkins.ingress.annotations }}
{{ toYaml .Values.jenkins.ingress.annotations | indent 4 }}
{{- end }}
  name: jenkins
spec:
  rules:
  - host: jenkins{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
    - jenkins{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
{{- if .Values.jenkins.ingress.tls.secretName }}
    secretName: "{{ .Values.jenkins.ingress.tls.secretName }}"
{{- else if .Values.cluster.ingress.tls.secretName }}
    secretName: "{{ .Values.cluster.ingress.tls.secretName }}"
{{- else if eq .Values.certmanager.production "true" }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
