{{- if eq .Values.certmanager.production "true" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ .Values.certmanager.email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsNames:
        - "*.{{ .Values.cluster.domain }}"
        - "{{ .Values.cluster.domain }}"
      # ACME DNS-01 provider configurations
      dns01:
        clouddns:
          # The project in which to update the DNS zone
          project: "{{ .Values.cluster.projectID }}"
          # A secretKeyRef to a google cloud json service account
          serviceAccountSecretRef:
            name: external-dns-gcp-sa
            key: credentials.json
{{- end }}