{{- if .Values.JenkinsXGitHub.password }}
apiVersion: v1
data:
  password: {{ .Values.JenkinsXGitHub.password | b64enc | quote }}
  username: {{ .Values.JenkinsXGitHub.username | b64enc | quote }}
kind: Secret
metadata:
  name: jx-pipeline-git-{{ .Values.gitops.gitKind | default "github" }}-{{ .Values.gitops.gitName | default "github" }}
  annotations:
    build.knative.dev/git-0: {{ .Values.gitops.server | default "https://github.com" }}
    jenkins.io/credentials-description: API Token for acccessing {{ .Values.gitops.server | default "https://github.com" }}
      Git service inside pipelines
    jenkins.io/name: {{ .Values.gitops.gitName | default "github" }}
    jenkins.io/url: {{ .Values.gitops.server | default "https://github.com" }}
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: {{ .Values.gitops.gitKind | default "github" }}
type: Opaque
{{- end }}